### PR TITLE
Add more files

### PR DESCRIPTION
**Pull request by thomas-mc-work**
Take more files into Account that are being ignored by Netbeans so far:
- changelog
- authors
- contributing

These special files are very popular in modern git repositories like github or gitlab.

### CODE REVIEW

**Comment by markiewb** [comment]
Instead of hardcoding more filenames: How about providing an option panel, where the user can configure it? I think a textfield for simple regex or comma-separated list of filenames would be fine.

**Comment by thomas-mc-work** [comment]
:+1: That would be the best solution. Unfortunately I'm unable to implement this as I haven't created any NB plugin before.

**Comment by markiewb** [comment]
@thomas-mc-work: It is not so difficult as you might think. It is mostly swing, with some specific NetBeans APIs to persist the settings. 

http://netbeans.org/kb/trails/platform.html

**Comment by chambelix** [comment]
Hi... When can I get the final nbm file to install it... the readme is aweome but this extra files make it better.

Good idea.

**Pull request merged**
